### ISSUE TITLE
VimeoUploadException in Vimeo.php line 365:

### ISSUE THREAD

**Issue by stojankukrika** [vinkla/laravel-vimeo#15]
HI,
I just add your script in laravel application, setup vimeo keys and try to upload, but get this error. Can you help me?

> VimeoUploadException in Vimeo.php line 365:

> Unable to get an upload ticket.[You must provide a valid authenticated access token.]

**Comment by vinkla** [comment]
Since this a Laravel wrapper for [the official Vimeo package](https://github.com/vimeo/vimeo.php) I suggest we ask @erunion and @Dashron about this.

**Comment by stojankukrika** [comment]
Can you do that,please?

**Comment by vinkla** [comment]
No, I'll only point in the right direction. It is your problem. Not mine.

**Comment by stojankukrika** [comment]
but I use your package and it doesn't works.

**Comment by erunion** [comment]
@stojankukrika Sounds like there's something funky with how you're using the library, can you email our support team? Someone there will get you sorted out. https://vimeo.com/help/contact#tech-api

**Comment by stojankukrika** [comment]
tnx @erunion.I just send a contact message, I hope you can solve mine problem. TNX.

**Comment by vinkla** [comment]
> but I use your package and it doesn't works.

That doesn't mean you can expect support from me. I've provided this package for free.
