### ISSUE TITLE
config/vimeo.php not created when vendor:publish

### ISSUE THREAD

**Issue by tarlusah** [vinkla/laravel-vimeo#19]
using laravel 5.3 and config/vimeo.php not created when vendor:publish

**Comment by vinkla** [comment]
Did you register the service provider?

**Comment by tarlusah** [comment]
yes i did,

**Comment by vinkla** [comment]
Please share your `app.php` file.

**Comment by tarlusah** [comment]
![screenshot from 2017-03-02 15 17 28](https://cloud.githubusercontent.com/assets/6928269/23498696/659e581a-ff5b-11e6-8baa-834701823e34.png)
![screenshot from 2017-03-02 15 17 21](https://cloud.githubusercontent.com/assets/6928269/23498697/65a56c4a-ff5b-11e6-8062-fb3349dd19a2.png)

**Comment by vinkla** [comment]
Okay, thanks. Could you also share the output when running `php artisan vendor:publish`?

**Comment by tarlusah** [comment]
![screenshot from 2017-03-02 16 11 01](https://cloud.githubusercontent.com/assets/6928269/23500484/d940a6fe-ff62-11e6-8805-0ddbf4289746.png)

**Comment by vinkla** [comment]
Weird, just tried this in one of my Laravel applications and it seems to work. Try updating to Laravel 5.4 and see if that works.

**Comment by tarlusah** [comment]
is it good if i hard copy the `vimeo.php` file

**Comment by vinkla** [comment]
Yeah, you can hard copy it. Shouldn't be a problem.

**Comment by tarlusah** [comment]
oke, thank you @vinkla, i really appreciate your help:)

**Comment by siddharthghedia** [comment]
` - Installation request for vinkla/vimeo ^3.7 -> satisfiable by vinkla/vimeo[3.7.0].
    - Conclusion: remove laravel/framework v5.4.36
    - Conclusion: don't install laravel/framework v5.4.36
    - vinkla/vimeo 3.7.0 requires illuminate/support 5.5.* -> satisfiable by illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.16|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.17|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.2|don't install laravel/framework v5.4.36
    - Installation request for laravel/framework (locked at v5.4.36, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.36].`

Getting this error while installing it on Laravel 5.4
