### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by hansgianfranco** [vinkla/laravel-vimeo#23]
Error, upload video but not return parameters video:
![captura de pantalla 2017-09-18 a la s 19 13 31](https://user-images.githubusercontent.com/6568256/30570252-b605f58c-9ca5-11e7-9a6c-7867e3303397.png)
![captura de pantalla 2017-09-18 a la s 19 13 57](https://user-images.githubusercontent.com/6568256/30570255-ba329c6e-9ca5-11e7-9eb3-f320b68a0982.png)
![captura de pantalla 2017-09-18 a la s 19 13 43](https://user-images.githubusercontent.com/6568256/30570256-ba52419a-9ca5-11e7-9728-76222cb725b5.png)

**Comment by vinkla** [comment]
Please ask in the [official Vimeo package](https://github.com/vimeo/vimeo.php). This is just a Laravel wrapper.
