### ISSUE TITLE
Dynamically set access_token?

### ISSUE THREAD

**Issue by justincone** [vinkla/laravel-vimeo#24]
I've created a multi-user web app, and I'm storing each user's Vimeo token in the database. 

Is there a way to dynamically set the access_token for a Vimeo connection? 

Thank you in advance for your assistance — and for creating this project!

**Comment by vinkla** [comment]
Hi @justincone, please open ask in [the official Vimeo package](https://github.com/vimeo/vimeo.php) repository. This is just a Laravel wrapper.
